version: "3.8"

services:
  app-dev:
#    image: javab7:latest
    build:
      context: .
    container_name: springboot-dev
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8080"
    restart: unless-stopped

#  app-prod:
#    build:
#      context: .
##    image: javab7:latest
#    container_name: springboot-prod
##    environment:
##      - SPRING_PROFILES_ACTIVE=prod
#    ports:
#      - "8081:8081"
#    restart: unless-stopped
